source 'https://rubygems.org'

#gem 'aws-sdk'
gem 'aws-sdk-dynamodb'
gem 'ox'
gem 'faraday'
gem 'fastest-csv'
#gem 'fastest_csv', git: 'https://github.com/custora/fastest-csv.git', tag: 'v0.8.2'
#gem 'activesupport'
gem 'pry'
